
<!DOCTYPE html>
<html>
<head>
    <title>This mail is from Inventory Management, Inya Lake Hotel</title>
    <style>
        body{font-family: Pyidaungsu;}
        table, th, td {
            border: 1px solid black;
            padding: 2px;
            border-collapse: collapse;
        }
        th {
            background-color: #04AA6D;
        }
        span {
            font-weight: bold;
        }
        .right {
        text-align: right;
        }
        .inProgress {
            color: orange;
        }
        .project {
            color: blue;

        }
        .grand {
            font-weight: bold;
        }
        .assign {
            color: violet;

        }
        .closed {
            color: gray;

        }
        p,.pending {
            color: red;
        }
        .room {
            color:darkblue;
        }
    </style>
</head>
<body>
    <h4>Product Distribution Ledger | Location : {{$location}}</h4>
   
<table>
    <thead>
        <tr>                               
          <th rowspan="2">Stock No.</th>
          <th rowspan="2">Name</th>
          <th rowspan="2">Unit</th>
          <th colspan="3">In</th>
          <th colspan="3">Out</th>
    </tr>
    <tr>
        
          <th>Qty</th>
          <th>Cost (USD)</th>
          <th>Cost (MMK)</th>
          <th>Qty</th>
          <th>Cost (USD)</th>
          <th>Cost (MMK)</th>
          
           
        </tr>
    </thead>
    <tbody>
    @foreach ($data2 as $datacategory)
    <tr>
        <td colspan="9">Category: ({{$datacategory->group_code}}) {{$datacategory->category->name}}</td>
    </tr>
    @foreach ($data as $dataeach)
    @if($datacategory->group_code == $dataeach->group_code)
    <tr>
            <td>{{ $dataeach->item->item_code }} </td>
            <td>{{ $dataeach->item->name }} </td>
            <td>{{ $dataeach->item->unit_measure }} </td>
            <td class="right">{{ $dataeach->total_in_qty }} </td>
            <td class="right">{{ $dataeach->total_in_usd }} </td>
            <td class="right">{{ $dataeach->total_in_mmk }} </td>
            <td class="right">{{ $dataeach->total_out_qty }} </td>
            <td class="right">{{ $dataeach->total_out_usd }} </td>
            <td class="right">{{ $dataeach->total_out_mmk }} </td>
          

    </tr>
    @endif
    @endforeach
    <tr>
        <td colspan="3">Sub Total </td>
        <td class="right">{{ $datacategory->total_in_qty }} </td>
        <td class="right">{{ $datacategory->total_in_usd }} </td>
        <td class="right">{{ $datacategory->total_in_mmk }} </td>
        <td class="right">{{ $datacategory->total_out_qty }} </td>
        <td class="right">{{ $datacategory->total_out_usd }} </td>
        <td class="right">{{ $datacategory->total_out_mmk }} </td>
    </tr>
   
   
    @endforeach
       
          
           
     

       
    </tbody>
  
</table>
<p>#Please note that this report is automatically generated by Inventory System.</p>

</body>
</html>