
<!DOCTYPE html>
<html>
<head>
    <title>This mail is from Case Management, Inya Lake Hotel</title>
    <style>
        table, th, td {
            border: 1px solid black;
            padding: 3px;
            border-collapse: collapse;
        }
        span {
            font-weight: bold;
        }
        .done {
        color: green;
        }
        .inProgress {
            color: orange;
        }
        .project {
            color: blue;

        }
        .assign {
            color: violet;

        }
        .closed {
            color: gray;

        }
        p,.pending {
            color: red;
        }
        .room {
            color:darkblue;
        }
    </style>
</head>
<body>
    <h3>Custom Complaints Report </h3>
<table>
    <thead>
        <tr>                               
            <th>#</th>
 
            <th>Defect</th>
            <th>Action</th>
            <th>Status</th>
            <th>Atten:</th>
            <th>Remark</th>
            <th>Since</th> 
           
        </tr>
    </thead>
    <tbody>
        @foreach ($data as $data)
        <tr>
           
           
            <td>{{ $loop->index+1}}</td>
            <td>{{$data->defect}} <span class="room">@
            @foreach ($selectedrooms as $room)
            @if($room->complaint_id == $data->id)
            {{ $room->name }},
            @endif
            @endforeach
            </span>
            </td>
            <td>{{$data->action}} </td>
            @if($data->status=='pending')  
          
            <td><span class="pending">{{$data->status}}</span> </td>
            @elseif($data->status=='inProgress')
            <td><span class="inProgress">{{$data->status}}</span> </td> 
            @elseif($data->status=='project')  
            <td><span class="project">{{$data->status}}</span> </td>   
            @elseif($data->status=='done')   
            <td><span class="done">{{$data->status}}</span> </td>    
            @elseif($data->status=='assign')    
            <td><span class="assign">{{$data->status}}</span> </td>  
            @elseif($data->status=='closed')    
            <td><span class="closed">{{$data->status}}</span> </td>       
            @endif
            <td>{{ $data->department_name }} </td>
            <td>{{ $data->remark }} </td>
            <td>{{ \Carbon\Carbon::parse($data->created_at)->diffForHumans() }} </td>
        </tr>
       
        @endforeach

    </tbody>
  
</table>
<p>#Please note that this report is automatically generated by Case Management System.</p>

</body>
</html>