
<!DOCTYPE html>
<html>
<head>
    <title>This mail is from Case Management, Inya Lake Hotel</title>
    <style>
        body{font-family: Pyidaungsu;}
        table, th, td {
            border: 1px solid black;
            padding: 2px;
            border-collapse: collapse;
        }
        th {
            background-color: #04AA6D;
        }
        span {
            font-weight: bold;
        }
        .right {
        text-align: right;
        }
        .inProgress {
            color: orange;
        }
        .project {
            color: blue;

        }
        .grand {
            font-weight: bold;
        }
        .assign {
            color: violet;

        }
        .closed {
            color: gray;

        }
        p,.pending {
            color: red;
        }
        .room {
            color:darkblue;
        }
    </style>
</head>
<body>
    <h4>Stock Balance Listing | Location : {{$location}}</h4>
   
<table>
    <thead>
        <tr>                               
          <th>Stock No.</th>
          <th>Name</th>
          <th>Specification</th>
          <th>Date In</th>
          <th>Exp Date</th>
          <th>Unit</th>
          <th>Price USD</th>
          <th>Price MMK</th>
          <th>Balance</th>
          <th>Total USD</th>
          <th>Total MMK</th>
            
           
        </tr>
    </thead>
    <tbody>
    @foreach ($data2 as $datatotal)
       
            
            @foreach ($data as $data1)
            @if($datatotal->item_id == $data1->item_id)
            <tr>            
            <td>{{ $data1->item->item_code }} </td>
            <td>{{ $data1->item->name }} </td>
            <td>{{ $data1->item->spec }} </td>
            <td>{{ $data1->received_date }} </td>
            @if($data1->expired_date)
            <td>{{$data1->expired_date}}</td>
            @else
            <td>NA</td>
            @endif
            <td>{{ $data1->item->unit_measure }} </td>
            <td class="right">{{ $data1->price_usd }} </td>
            <td class="right">{{ $data1->price_mmk }} </td>
            <td class="right">{{ $data1->total_qty }} </td>
            <td class="right">{{ $data1->total_usd }} </td>
            <td class="right">{{ $data1->total_mmk }} </td>
            </tr>  
            @endif
            @endforeach
            <tr>
            <td colspan="8" class="right">Subtotal</td>
            <td class="right">{{ $datatotal->total_qty }} </td> 
            <td class="right">{{ $datatotal->total_usd }} </td> 
            <td class="right">{{ $datatotal->total_mmk }} </td> 
         </tr>
    @endforeach
       
          
           
     

       
    </tbody>
  
</table>
<p>#Please note that this report is automatically generated by Inventory System.</p>

</body>
</html>