
<!DOCTYPE html>
<html>
<head>
    <title>This mail is from Inventory Management, Inya Lake Hotel</title>
    <style>
        body{font-family: Pyidaungsu;}
        table, th, td {
            border: 1px solid black;
            padding: 2px;
            border-collapse: collapse;
        }
        th {
            background-color: #04AA6D;
        }
        span {
            font-weight: bold;
        }
        .right {
        text-align: right;
        }
        .inProgress {
            color: orange;
        }
        .project {
            color: blue;

        }
        .grand {
            font-weight: bold;
        }
        .assign {
            color: violet;

        }
        .closed {
            color: gray;

        }
        p,.pending {
            color: red;
        }
        .room {
            color:darkblue;
        }
    </style>
</head>
<body>
    <h4>Stock Taking Print Form | Location : {{$location}}</h4>
   
<table>
    <thead>
  
    <tr>
        
          <th>Item Code</th>
          <th>Item Name</th>
          <th>Specifications</th>
          <th>UM</th>
          <th>Quantity</th>      
          
           
        </tr>
    </thead>
    <tbody>
    @foreach ($data2 as $datacategory)
    <tr>
        <td>Category: {{$datacategory->group_code}} | {{ $datacategory->name }} </td>
    </tr>
  
   
   
    @endforeach
       
          
           
     

       
    </tbody>
  
</table>
<p>#Please note that this report is automatically generated by Inventory System.</p>

</body>
</html>