
<!DOCTYPE html>
<html>
<head>
    <title>Users @ Inya Lake Hotel</title>
    <style>
        table, th, td {
            border: 1px solid black;
            padding: 3px;
            border-collapse: collapse;
        }
        span {
            font-weight: bold;
        }
        .done {
        color: green;
        }
        .inProgress {
            color: orange;
        }
        .project {
            color: blue;

        }
        .assign {
            color: violet;

        }
        .closed {
            color: gray;

        }
        p,.pending {
            color: red;
        }
        .room {
            color:darkblue;
        }
    </style>
</head>
<body>
    <h3>Users </h3>
    <table>
                        <thead>
                            <tr>
                              
                               
                                <th>Name</th>
                                <th>Email</th>
                                <th>Registered Date</th>
                                <th>Department</th>
                                
                            </tr>
                        </thead>
                        <tbody>
                        @foreach ($data as $data)
        <tr>
           
            <td>{{ $data->name }} </td>
            <td>{{ $data->email }} </td>      
            <td>{{ \Carbon\Carbon::parse($data->created_at)->diffForHumans() }} </td>
            <td>{{ $data->department->name }} </td>
        </tr>
       
        @endforeach
        </tbody>
  
  </table>
                     
<p>#Please note that this report is automatically generated by Case Management System.</p>

</body>
</html>